apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{RELEASE_NAME}}
  labels:
    app: {{RELEASE_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{RELEASE_NAME}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{RELEASE_NAME}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: /prometheus
    spec:
      containers:
        - name: {{RELEASE_NAME}}
          image: {{IMAGE_REG_PATH}}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
#          env:                         # SYSTEM Properties
#            - name: SPRING_PROFILE
#              value: "prd"
          livenessProbe:                    # Health check - 실패시 Pod 재기동
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:                    # 가동여부 확인
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 300Mi
            requests:
              cpu: 1000m
              memory: 300Mi
      imagePullSecrets:
        - name: regcred
