apiVersion: v1
kind: Service
metadata:
  name: {{RELEASE_NAME}}
  labels:
    secured: false
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{RELEASE_NAME}}